### ISSUE TITLE
Failed to decode config file

### ISSUE THREAD

**Issue by danhardman** [BurntSushi/toml#150]
I keep getting error: `Failed to decode config file: Near line 0 (last key parsed ''): Bare keys cannot contain '.'.`

I'm using atom and encoding as UTF-8, there is no BOM. I've tried other text-editors and specified with and without BOM. My file is:

```toml
version = "1.1.1"

[application]
port = ":443"
dbConnectionString = "user:pass@/db?charset=utf8&parseTime=True&loc=Local"
certFile = "server.pem"
privKeyFile = "server.key"

[apiKeys]
sendGrid = "key"
stripe = "key"

[settings]
name = "Foo Bar Ltd"
adminEmail = "example@example.co.uk"
domain = "localhost:443"
```

Any suggestions?
