### ISSUE TITLE
usage question

### ISSUE THREAD

**Issue by rhd** [BurntSushi/toml#177]
Hi, 

I've been flailing for a while at this - can anyone help me parse a recursive depth toml file that looks like this?

```toml
key = "val"

[R001]
summery = "some string"

  [R001.1]
  summery = "some string"

    [R001.1.25]
    summery = "some string"
    test = true
  
    [R001.1.30]
    summery = "some string"
    test = true
  
  [R001.2]
  summery = "some string"
  test = true
  
[R002]
summery = "some string"
```

Update: I meant to add that the format is not fixed. We could have a `R003`, `R004`, etc... and same goes for the rest of the layers.
