### ISSUE TITLE
Is it possible to (re)encode to an existing file without overwriting comments and blank lines?

### ISSUE THREAD

**Issue by onodera-punpun** [BurntSushi/toml#208]
Example:

Original file:
```toml
# Your monero-rpc username and password.
username = "onodera"
password = "seekrit"

# The currency to compare XMR to, choose between `USD` or `EUR`.
currency = "USD"
```

Code:
```go
config.Currency = "EUR"
buf := new(bytes.Buffer)
toml.NewEncoder(buf).Encode(config)
ioutil.WriteFile(path.Join(d, "runtime", "config.toml"), buf.Bytes(), 0664)
```

Output:
```toml
username = "username"
password = "password"
currency = "EUR"
```

Desired output:
```toml
# Your monero-rpc username and password.
username = "username"
password = "password"

# The currency to compare XMR to, choose between `USD` or `EUR`.
currency = "EUR"
```
