### ISSUE TITLE
Custom Type Slice support when Unmarshaling

### ISSUE THREAD

**Issue by sp3c1** [BurntSushi/toml#224]
Trying unmarshalling TOML like that

```TOML
[routes]
test = "teststromg"
    [gets]
        [[get]]
            path = "/"
            auth = false
        [[get]]
            path = "/header"
            header = "json-content"
        [[get]]
            path = "/redirect"
            redirect = "http://somewhere"
        [[get]]
            path = "/authed"
            auth = true
```
With following structs

```Go
type Get struct {
	Path     string
	Auth     bool
	Redirect string
	Header   string
}

type Routes struct {
	Gets []Get
}

type Config struct {
	Routes Routes
}
``` 
Gives empty array in `Routes.Gets` 

When definition is changed to array instead of slice it picks it up (obviously).
