### ISSUE TITLE
Boolean always parsed as true if key is named "loop"

### ISSUE THREAD

**Issue by cezarmathe** [BurntSushi/toml#249]
I've encountered an issue where I had a configuration file like this:
```toml
default_display = ":0"
loop = false
slideshow_delay = 10
force_resolution = "800x480"
```

and a struct like this:
```go
type Cfg struct {
	Loop            bool      `toml:"loop"`
	SlideShowDelay  int       `toml:"slideshow_delay"`
	ForceResolution string    `toml:"force_resolution"`
}
```

and after parsing, Cfg.Loop would always be true, even if in the configuration file it was set to false. I fixed the issue by renaming it from "loop" to "img_loop", and now they look like this:
```toml
default_display = ":0"
img_loop = false
slideshow_delay = 10
force_resolution = "800x480"
```
```go
type Cfg struct {
	Loop            bool      `toml:"img_loop"`
	SlideShowDelay  int       `toml:"slideshow_delay"`
	ForceResolution string    `toml:"force_resolution"`
}
```
