### ISSUE TITLE
Parsing toml files does not always produce the expected results

### ISSUE THREAD

**Issue by IvanGao01** [BurntSushi/toml#363]
This is source code:
```golang
package main

import (
	"fmt"

	"github.com/BurntSushi/toml"
)

type Config struct {
	StartTime string `toml:"start-time"`
	EndTime string `toml:"end-time"`
	Format string `toml:"format"`
	//Interval time.Duration `toml:"internal"`
	MetricBatchSize int `toml:"metric-batch-size"`
	InfluxDB InfluxDB `toml:"influxdb"`
	Streams []Stream `toml:"stream"`
}

type InfluxDB struct {
	Urls []string `toml:"urls"`
	Database string `toml:"database"`
	RetentionPolicy string `toml:"retention-policy"`
	Timeout int `toml:"timeout"`
}

type Stream struct {
	//Interval time.Duration `toml:"internal"`
	Measurement string `toml:"measurement"`
	Tag []Tag `toml:"tag"`
	Field []Field `field:"field"`
}

type Tag struct {
	Key string
	Value []string
	ValuesTag int
	
}

type Field struct {
	Key string
	Value []interface{}
	ValuesTag int
	ValueType string
}

func main() {
	var config Config
	if _, err := toml.DecodeFile("etc/sample.conf", &config); err != nil {

	}
	fmt.Printf("startTime: %v\n", config.StartTime)
}
```

This is the toml file in the code: 

```toml
# global

# Data generation interval
interval= "10"
## metric_batch_size metrics.
metric-batch-size= "5000"
# start-time
start-time= "2022-01-01T00:00:00Z"

# end-time
end-time= "2022-01-02T00:00:00Z"

# format default rfc3339
format = "rfc3339"


[influxdb]
urls = ["http://127.0.0.1:8086"]
database = "telegraf"
retention-policy = ""
timeout = "5s"
```

I ran it more than ten times, and only two times returned the correct results:

```
➜  stream-gen git:(main) ✗ go run main.go       
startTime: 
➜  stream-gen git:(main) ✗ go run main.go
startTime: 
➜  stream-gen git:(main) ✗ go run main.go
startTime: 
➜  stream-gen git:(main) ✗ go run main.go
startTime: 
➜  stream-gen git:(main) ✗ go run main.go
startTime: 
➜  stream-gen git:(main) ✗ go run main.go
startTime: 
➜  stream-gen git:(main) ✗ go run main.go
startTime: 2022-01-01T00:00:00Z
➜  stream-gen git:(main) ✗ go run main.go
startTime: 
➜  stream-gen git:(main) ✗ go run main.go
startTime: 
➜  stream-gen git:(main) ✗ go run main.go
startTime: 2022-01-01T00:00:00Z
➜  stream-gen git:(main) ✗ go run main.go
startTime: 
```

environmental information: 

Golang Version: go1.18.3 darwin/arm64

github.com/BurntSushi/toml v1.2.0
