### ISSUE TITLE
Support newlines in inline tables

### ISSUE THREAD

**Issue by theoparis** [BurntSushi/toml#380]
I tried to use traefik, which uses this library for supporting toml config files.

Example traefik config that I used
```toml
certificatesResolvers.leresolver = {
	acme = {
		email = "theop@example.com",
		tlsChallenge = {},
	},
}

http.routers.main = {
	rule = "Host(`code.example.com`)",
	tls = {
		certResolver = "leresolver",
	},
}
```

The error from docker compose:
```
command traefik error: toml: line 1 (last key \"certificatesResolvers.leresolver\"): newlines not allowed within inline tables
```

Please let me know if this an issue with traefik specifically and not a parser issue.

See  https://github.com/toml-lang/toml/pull/904
