### ISSUE TITLE
Export "Unify"-like Public API?

### ISSUE THREAD

**Issue by mitchellh** [BurntSushi/toml#4]
This may be related to #3. I have a TOML file that looks something like this:

``` toml
[things]

[things.something]
type = "widget"
key = "value"
etc.
```

I can't decode the "things" until I know the "type." Ideally what I want to do is something like this:

``` go
type Top struct {
    Things map[string]interface{}
}

type Widget struct {
    Key string
}

// Later on...
var widget Widget
toml.Unify(top.Things["something"], &widget)
```

(I realize that isn't the type signature of Unify at the moment)

Is there a better way to do this?
