### ISSUE TITLE
How to unmarshal tagged unions?

### ISSUE THREAD

**Issue by cal-pratt** [BurntSushi/toml#401]
How can I write my structs/parsing logic to handle unmarshalling tagged unions? I have documents with deeply nested content, and many cases where there are lists with various different possible types in the one container. 

For example, say I have the following toml

```toml
[[items]]
  foo = "foo"
  [items.data]
    fizz = "fizz"
    buzz = "buzz"
[[items]]
  bar = "bar"
  [items.data]
    fizz = "fizz"
    buzz = "buzz"
```

Which in yaml looks like this:

```
items:
- foo: foo
  data:
    fizz: fizz
    buzz: buzz
- bar: bar
  data:
    fizz: fizz
    buzz: buzz
```

This is as close as I could get, but it still doesn't feel quite right.

```go
type Data struct {
    Fizz string
    Buzz string
}
type Foo struct {
    Foo string
    Data Data
}
type Bar struct {
    Bar string
    Data Data
}
type Doc struct {
    Items []struct{
        *Foo
        *Bar
    }
}
```

This example breaks down if you have any overlapping contents. A random sub-struct will be chosen for the contents if its present in both, meaning the data would be hard to grok.

I've also looked at using the unmarshal overrides on the structs like `Unmarshaler.UnmarshalTOML`, but this gives me only a map to work with. Right now, I still need to unmarshal the `Data` structs. I just want to tell the decoder what struct to start using and then continue on with its normal logic. If I use `UnmarshalTOML` near the root of the document, I have to manually assemble the entire structure, which defeats a lot of the purpose here.

Any thoughts on this? Or am I missing something simple?
