### ISSUE TITLE
Key 'gitrdone' has already been defined

### ISSUE THREAD

**Issue by joe-at-startupmedia** [BurntSushi/toml#429]
I'm pretty sure this is illegal and probably outside of the scope of this project.

If I try to parse a struct likeso:

```golang
type Decoder struct {
   Gitrdone   CoolRedneckStuff
}
```

And then I have this in my toml:

```toml
[gitrdone]
enabled = true
some_other_prop = [ 'mud_tires' ]

[gitrdone]
enabled = true
some_other_prop = [ 'grill_guard' ]
```

Is it possible to parse these into a slice of a the struct type whereby:

```golang
type Decoder struct {
   Gitrdone   []CoolRedneckStuff
}
```
