### ISSUE TITLE
Structs not decoding

### ISSUE THREAD

**Issue by marcus-downing** [BurntSushi/toml#52]
Am I doing this wrong? My toml:

``` toml
debug = true

[categories]

  [serious]
  name = "Serious"
  folders = [ "Serious" ]

  [start]
  name = "Starters"
  folders = [ "Semi-serious", "Mood", "Dance", "Action" ]

  [long]
  name = "Long"
  folders = [ "Long" ]

  [christmas]
  name = "Christmas"
  folders = [ "Christmas" ]

  [halloween]
  name = "Halloween"
  folders = [ "Halloween" ]

  [meta]
  name = "Meta"
  folders = [ "Meta" ]

  [buffer]
  name = "Buffers"
  folder = [ "Buffer" ]
```

And my Go (simplified):

``` go
type Configuration struct {
    Debug             bool
    Categories        map[string]Category
}

type Category struct {
    Name    string
    Folders []string
}

configData := ...
var config Configuration = Configuration{...}
if _, err := toml.Decode(string(configData), &config); err != nil {
    fmt.Println("Error decoding config.toml:", err)
} else {
    fmt.Printf("Config: %#v\n", Config)
}
```

The output:

``` go
Config: config.Configuration{Debug:true, Categories:map[string]config.Category{}}
```

This looks very similar to your `servers` example, but the `Categories` value comes out empty. Am I doing something wrong?
