### ISSUE TITLE
question about custom types

### ISSUE THREAD

**Issue by davidbirdsong** [BurntSushi/toml#85]
I'm using your example to Unmarshal a custom ```duration``` type from the README. I'm able to Unmarshal, but can you advise on how to Encode or Marshal?

I ran into problems with ```can't encode an anonymous field that is not a struct```. In searching around, I figured I could avoid the headache by modifying the duration type to only include a ```time.Duration``` field like so:

```golang
type duration struct {
	d time.Duration
}
func (d *duration) MarshalText() ([]byte, error) {
	return []byte(d.d.String()), nil
}
func (d *duration) UnmarshalText(text []byte) error {
	var err error
	d.d, err = time.ParseDuration(string(text))
	return err
}
```
This got me farther in that the Encode succeeds, but the output is not useful. Here's a section with a ```duration``` type:

```toml
[Heka]
  Connect = "tcp://127.0.0.1:5565"
  LogPoolSize = 100
  [Heka.log_every]
```

When what I'm hoping to yield is:
```toml
[Heka]
  Connect = "tcp://127.0.0.1:5565"
  LogPoolSize = 100
  log_every = "15s"
```

Can you set me straight?
