### ISSUE TITLE
Decoder: support all valid TOML floats

### ISSUE THREAD

**Issue by simleb** [BurntSushi/toml#98]
Currently, `1e2` and `0.1e2` and their `E` variants are not supported. The spec recommends support for these examples:

```toml
# fractional
flt1 = +1.0
flt2 = 3.1415
flt3 = -0.01

# exponent
flt4 = 5e+22
flt5 = 1e6
flt6 = -2E-2

# both
flt7 = 6.626e-34
```

Ideally, underscores should also work in floats

```toml
flt8 = 9_224_617.445_991_228_313
flt9 = 1e1_000
```

but this is less critical.
